// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARjHqgNDvmNBfa2LKAYr_J3uqT4W7s7Gg',
    appId: '1:616192718361:web:d472c2e2e3d4eb7d82dc88',
    messagingSenderId: '616192718361',
    projectId: 'live-bus-tracking-app-16ac8',
    authDomain: 'live-bus-tracking-app-16ac8.firebaseapp.com',
    storageBucket: 'live-bus-tracking-app-16ac8.firebasestorage.app',
    measurementId: 'G-RY63NJ1L2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgzJHAHW2S5u8ynHMil3qX8CYFUNRNNqc',
    appId: '1:616192718361:android:5973ef4c8e1c80a082dc88',
    messagingSenderId: '616192718361',
    projectId: 'live-bus-tracking-app-16ac8',
    storageBucket: 'live-bus-tracking-app-16ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV7IXCI6qV8TyVy524PY_5WFqFL5NxKog',
    appId: '1:616192718361:ios:761d9bd34c63af9e82dc88',
    messagingSenderId: '616192718361',
    projectId: 'live-bus-tracking-app-16ac8',
    storageBucket: 'live-bus-tracking-app-16ac8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV7IXCI6qV8TyVy524PY_5WFqFL5NxKog',
    appId: '1:616192718361:ios:761d9bd34c63af9e82dc88',
    messagingSenderId: '616192718361',
    projectId: 'live-bus-tracking-app-16ac8',
    storageBucket: 'live-bus-tracking-app-16ac8.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARjHqgNDvmNBfa2LKAYr_J3uqT4W7s7Gg',
    appId: '1:616192718361:web:a8abecd1fcef25e482dc88',
    messagingSenderId: '616192718361',
    projectId: 'live-bus-tracking-app-16ac8',
    authDomain: 'live-bus-tracking-app-16ac8.firebaseapp.com',
    storageBucket: 'live-bus-tracking-app-16ac8.firebasestorage.app',
    measurementId: 'G-X7D9WCCFD7',
  );
}
